# Generated by Django 2.0.3 on 2018-03-22 19:36

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attachment_file', models.ImageField(upload_to='', verbose_name='Attachment file')),
                ('object_id', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_file', models.ImageField(upload_to='', verbose_name='Archivo de imagen')),
                ('alt_text', models.CharField(blank=True, max_length=200, verbose_name='Alternative text')),
                ('object_id', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
            ],
        ),
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(verbose_name='URL of the link')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='Title of the link')),
                ('object_id', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True, verbose_name='Nombre del proyecto')),
                ('slug', models.SlugField(blank=True, editable=False)),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Fecha de comienzo')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Fecha de finalización')),
                ('project_format', models.CharField(choices=[('ar', 'Arquitectura'), ('we', 'Web')], max_length=2, verbose_name='Formato')),
                ('promoter', models.TextField(blank=True, null=True, verbose_name='Promotor')),
                ('author_text', models.TextField(blank=True, null=True, verbose_name='Autor')),
                ('gratitude_text', models.TextField(blank=True, null=True, verbose_name='Texto de agradecimientos')),
                ('main_image', models.ImageField(blank=True, upload_to='', verbose_name='Imagen principal')),
                ('summary', models.TextField(blank=True, null=True, verbose_name='Resumen')),
                ('body', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Texto')),
            ],
        ),
    ]
